name: Test Pull Request

on:
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Acceptance Test
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x

    - name: Checkout
      uses: actions/checkout@v3

    - name: Get Stack Distribution Name
      id: distro
      run: |
        # Extract distro from repo name:
        # paketo-buildpacks/jammy-tiny-stack --> jammy
        distro="$(echo "${{ github.repository }}" | sed 's/^.*\///' | sed 's/\-.*$//')"
        echo "Ubuntu distribution: ${distro}"
        printf "::set-output name=distro::%s\n" "${distro}"

    - name: Run Acceptance Tests
      run: |
        if [[ "${{ steps.distro.outputs.distro }}" == "bionic" ]]; then
          export "EXPERIMENTAL_ATTACH_RUN_IMAGE_SBOM=true"
        fi

        ./scripts/test.sh --clean

  upload:
    name: Upload Workflow Event Payload
    runs-on: ubuntu-latest
    steps:
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: event-payload
        path: ${{ github.event_path }}
